
paths:
  data_dir: dfa_data
  checkpoint_dir: /Users/cschaefe/dfa_checkpoints

audio:
  sample_rate: 22050
  n_filters: 1024
  n_mels: 80
  win_length: 1024
  hop_length: 256
  fmin: 0
  fmax: 8000
  normalizer: 'MelGAN'

model:
  lstm_dim: 128
  conv_dim: 64