
paths:
  dataset_dir: /Volumes/data/datasets/ASVoice2
  metadata_path: /Volumes/data/datasets/ASVoice2/transformer_tts/phonemized_metadata.txt
  data_dir: dfa_data
  checkpoint_dir: /Volumes/data/logs/dfa
  precomputed_mels: /Volumes/data/datasets/ASVoice2/transformer_tts/mels.MelGAN

audio:
  sample_rate: 22050
  n_filters: 1024
  n_mels: 80
  win_length: 1024
  hop_length: 256
  fmin: 0
  fmax: 8000

model:
  lstm_dim: 128
  conv_dim: 64

durations:
  method: 'dijkstra' # options: [dijkstra, beam]